MERGE INTO RAW.NEWS_ARTICLES_RAW t
USING RAW.NEWS_ARTICLES_LANDING s
ON t.ARTICLE_KEY = s.ARTICLE_KEY

WHEN NOT MATCHED THEN
INSERT
(
    ARTICLE_KEY,
    PROVIDER,
    QUERY_NAME,
    QUERY_TEXT,
    SOURCE_NAME,
    SOURCE_ID,
    AUTHOR,
    TITLE,
    DESCRIPTION,
    ARTICLE_URL,
    IMAGE_URL,
    PUBLISHED_AT,
    LANGUAGE,
    COUNTRY,
    CATEGORY,
    BATCH_ID,
    INGESTED_AT,
    RAW_JSON
)
VALUES
(
    s.ARTICLE_KEY,
    s.PROVIDER,
    s.QUERY_NAME,
    s.QUERY_TEXT,
    s.SOURCE_NAME,
    s.SOURCE_ID,
    s.AUTHOR,
    s.TITLE,
    s.DESCRIPTION,
    s.ARTICLE_URL,
    s.IMAGE_URL,
    s.PUBLISHED_AT,
    s.LANGUAGE,
    s.COUNTRY,
    s.CATEGORY,
    s.BATCH_ID,
    s.INGESTED_AT,
    PARSE_JSON(s.RAW_JSON)
);